version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
  build-and-push:
    environment:
      IMAGE_NAME: sdevilcry/front.vincelivemix
    docker:
      - image: circleci/node:12.18.1
    steps:
      - setup_remote_docker:
          docker_layer_caching: false # Plan is disabled
      - attach_workspace:
          at: .
      - run: |
          IMAGE_TAG="0.0.${CIRCLE_BUILD_NUM}"
          docker build -t $IMAGE_NAME:latest -f Dockerfile .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  version: 2
  build-and-publish:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
          filters:
            branches:
              only: master
